- create:
    ~/.ssh:
      mode: 0700
- link:
    ~/.oh-my-zsh/oh-my-zsh.sh:
        path: shells/omz/oh-my-zsh.sh
- shell:
    # git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
    git -C ~/.oh-my-zsh/custom/plugins clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git
    git -C ~/.oh-my-zsh/custom/plugins clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git
