- link:
    ~/.zshrc:       shells/zsh/zshrc
    ~/.antigen.zsh: shells/zsh/antigen.zsh

- shell:
    - command: apt update && apt install zsh -y
      stdout: true
      stderr: true
    - [chsh -s $(which zsh), Making zsh the default shell]