- defaults:
    link:
      create: true
      relink: true
      force: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]

- clean: [
    '~',
    '~/.config'
]